[build]
  publish = "public"
  command = "npm install && hugo --minify"

[build.environment]
  HUGO_VERSION = "0.95.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

[functions]
  node_bundler = "esbuild"